import { Product, CarrierTrip, Order, EscrowAccount, UserDevice, ActivityLog, UserProfile } from '../types';

export const MOCK_USERS: Record<string, UserProfile> = {
  buyer: {
    id: 'usr_buyer_1',
    email: 'buyer@diasporalink.com',
    full_name: 'Grace Mutoni',
    phone_number: '+1 416 555 0192',
    role: 'buyer',
    country: 'CA',
    is_kyc_verified: true,
    is_approved: true,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  vendor_rwanda: {
    id: 'usr_vrw_1',
    email: 'export@gishwatitea.rw',
    full_name: 'Gishwati Tea Producers Cooperative',
    phone_number: '+250 788 392 010',
    role: 'vendor_rwanda',
    country: 'RW',
    is_kyc_verified: true,
    is_approved: true,
    rdb_tin_number: 'TIN-109283745 (RDB Certified)',
    momo_number: '+250 788 392 010',
    momo_provider: 'MTN',
    created_at: new Date(Date.now() - 86400000 * 60).toISOString(),
  },
  vendor_canada: {
    id: 'usr_vca_1',
    email: 'logistics@greatlakesdiaspora.ca',
    full_name: 'Great Lakes Importers Inc',
    phone_number: '+1 647 882 1092',
    role: 'vendor_canada',
    country: 'CA',
    is_kyc_verified: true,
    is_approved: true,
    cra_business_number: 'BN-884920194 (CRA Registered)',
    stripe_account_id: 'acct_1Nk02910283',
    created_at: new Date(Date.now() - 86400000 * 45).toISOString(),
  },
  courier: {
    id: 'usr_courier_1',
    email: 'david.mugisha@gmail.com',
    full_name: 'David Mugisha (Air Courier)',
    phone_number: '+250 788 112 334',
    role: 'logistics_courier',
    country: 'RW',
    is_kyc_verified: true,
    is_approved: true,
    created_at: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  admin: {
    id: 'usr_admin_1',
    email: 'admin@diasporalink.com',
    full_name: 'Emmanuel Habumugisha (System Admin)',
    phone_number: '+250 788 000 999',
    role: 'admin',
    country: 'RW',
    is_kyc_verified: true,
    is_approved: true,
    created_at: new Date(Date.now() - 86400000 * 120).toISOString(),
  },
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    vendor_id: 'usr_vrw_1',
    vendor_name: 'Gishwati Tea Producers Cooperative',
    title: 'Gishwati Organic Black Export Tea',
    description: 'High-altitude organic orthodox black tea harvested from Gishwati Cloud Forest estates. Deep aroma and rich malt flavor profile.',
    category: 'coffee_tea',
    origin_country: 'RW',
    target_corridor: 'KGL_YYZ',
    price_cad: 18.50,
    price_rwf: 22800,
    weight_kg: 0.5,
    hs_tariff_code: '0902.30.10 (Duty Free)',
    images: ['https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=800&auto=format&fit=crop'],
    stock_quantity: 120,
    is_active: true,
    in_stock: true,
    is_unlisted: false,
    rdb_certified: true,
    likes_count: 84,
    purchase_count: 142,
    rating: 4.9,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'prod_2',
    vendor_id: 'usr_vrw_1',
    vendor_name: 'Kivu Belt Specialty Coffee',
    title: 'Lake Kivu Single Origin Arabica Coffee Beans',
    description: 'Specialty grade Red Bourbon 100% Arabica coffee grown on the fertile volcanic shores of Lake Kivu. Notes of dark chocolate, berry nectar, and cane sugar.',
    category: 'coffee_tea',
    origin_country: 'RW',
    target_corridor: 'KGL_YYZ',
    price_cad: 24.00,
    price_rwf: 29500,
    weight_kg: 1.0,
    hs_tariff_code: '0901.11.00 (RDB Certified)',
    images: ['https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=800&auto=format&fit=crop'],
    stock_quantity: 85,
    is_active: true,
    in_stock: true,
    is_unlisted: false,
    rdb_certified: true,
    likes_count: 156,
    purchase_count: 210,
    rating: 5.0,
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: 'prod_3',
    vendor_id: 'usr_vrw_1',
    vendor_name: 'Nyamirambo Women’s Center',
    title: 'Handcrafted Imigongo Geometric Art Wall Plaque',
    description: 'Traditional Rwandan Imigongo wall art handmade by artisan women cooperatives using authentic earth pigments and natural relief crafting.',
    category: 'crafts',
    origin_country: 'RW',
    target_corridor: 'KGL_YYZ',
    price_cad: 65.00,
    price_rwf: 80000,
    weight_kg: 1.5,
    hs_tariff_code: '9701.10.00 (Handicraft Exemption)',
    images: ['https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=800&auto=format&fit=crop'],
    stock_quantity: 25,
    is_active: true,
    in_stock: true,
    is_unlisted: false,
    rdb_certified: true,
    likes_count: 98,
    purchase_count: 36,
    rating: 4.8,
    created_at: new Date(Date.now() - 86400000 * 12).toISOString(),
  },
  {
    id: 'prod_4',
    vendor_id: 'usr_vrw_1',
    vendor_name: 'House of Tayo Fashion',
    title: 'Handwoven Agaseke Peace Basket (Gold Edition)',
    description: 'Iconic Rwandan Peace Basket woven from sisal fiber and sweetgrass. Symbol of diaspora heritage and elegant home decor.',
    category: 'decor',
    origin_country: 'RW',
    target_corridor: 'KGL_YYZ',
    price_cad: 45.00,
    price_rwf: 55500,
    weight_kg: 0.8,
    hs_tariff_code: '4602.19.00',
    images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop'],
    stock_quantity: 40,
    is_active: true,
    in_stock: true,
    is_unlisted: false,
    rdb_certified: true,
    likes_count: 112,
    purchase_count: 64,
    rating: 4.9,
    created_at: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  {
    id: 'prod_5',
    vendor_id: 'usr_vca_1',
    vendor_name: 'Great Lakes Importers Inc',
    title: 'Modern Rwandan History & Culture Hardcover Book',
    description: 'Comprehensive literary anthology exploring 100 years of Rwandan cultural resilience, art, and diaspora storytelling published in English & Kinyarwanda.',
    category: 'books',
    origin_country: 'CA',
    target_corridor: 'YYZ_KGL',
    price_cad: 32.00,
    price_rwf: 39400,
    weight_kg: 0.9,
    hs_tariff_code: '4901.99.00 (Educational)',
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=800&auto=format&fit=crop'],
    stock_quantity: 60,
    is_active: true,
    in_stock: true,
    is_unlisted: false,
    rdb_certified: true,
    likes_count: 45,
    purchase_count: 28,
    rating: 4.7,
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'prod_6',
    vendor_id: 'usr_vrw_1',
    vendor_name: 'Gishwati Tea Producers Cooperative',
    title: 'Premium Raw Organic Rwandan Honey (500g)',
    description: 'Pure wildflower honey collected from beekeepers adjacent to Nyungwe and Gishwati national reserves. Unfiltered with rich enzymatic properties.',
    category: 'gifts',
    origin_country: 'RW',
    target_corridor: 'KGL_YYZ',
    price_cad: 22.00,
    price_rwf: 27100,
    weight_kg: 0.6,
    hs_tariff_code: '0409.00.00',
    images: ['https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=800&auto=format&fit=crop'],
    stock_quantity: 90,
    is_active: true,
    in_stock: true,
    is_unlisted: false,
    rdb_certified: true,
    likes_count: 67,
    purchase_count: 89,
    rating: 4.9,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
];

export const INITIAL_CARRIER_TRIPS: CarrierTrip[] = [
  {
    id: 'trip_1',
    courier_id: 'usr_courier_1',
    courier_name: 'David Mugisha (RwandAir Traveler)',
    flight_number: 'WB 302',
    airline: 'RwandAir',
    departure_airport: 'KGL',
    arrival_airport: 'YYZ',
    departure_date: '2026-08-25',
    total_capacity_kg: 23.0,
    available_capacity_kg: 14.5,
    rate_per_kg_cad: 12.00,
    rate_per_kg_rwf: 14800,
    status: 'listed',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'trip_2',
    courier_id: 'usr_courier_1',
    courier_name: 'David Mugisha (RwandAir Traveler)',
    flight_number: 'ET 602',
    airline: 'Ethiopian Airlines',
    departure_airport: 'KGL',
    arrival_airport: 'YYZ',
    departure_date: '2026-09-02',
    total_capacity_kg: 30.0,
    available_capacity_kg: 22.0,
    rate_per_kg_cad: 11.50,
    rate_per_kg_rwf: 14100,
    status: 'listed',
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_1',
    order_number: 'ORD-2026-88219',
    buyer_id: 'usr_buyer_1',
    buyer_name: 'Grace Mutoni',
    vendor_id: 'usr_vrw_1',
    vendor_name: 'Gishwati Tea Producers Cooperative',
    courier_id: 'usr_courier_1',
    items: [
      {
        product_id: 'prod_1',
        title: 'Gishwati Organic Black Export Tea',
        quantity: 2,
        unit_price_cad: 18.50,
        unit_price_rwf: 22800,
        weight_kg: 0.5,
        image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=800',
      },
      {
        product_id: 'prod_2',
        title: 'Lake Kivu Single Origin Arabica Coffee Beans',
        quantity: 1,
        unit_price_cad: 24.00,
        unit_price_rwf: 29500,
        weight_kg: 1.0,
        image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=800',
      },
    ],
    corridor: 'KGL_YYZ',
    total_cad: 61.00,
    total_rwf: 75100,
    shipping_fee_cad: 18.00,
    customs_duty_cad: 0.00,
    payment_method: 'STRIPE',
    status: 'in_flight',
    escrow_status: 'holding',
    awb_number: 'AWB-KGL-88219',
    qr_seal_code: 'RW-SEAL-8842',
    delivery_address: {
      street: '450 Yonge St, Suite 1200',
      city: 'Toronto',
      province_or_state: 'ON',
      postal_code: 'M4Y 1W9',
      country: 'CA',
      recipient_name: 'Grace Mutoni',
      recipient_phone: '+1 416 555 0192',
    },
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
];

export const INITIAL_ESCROW: EscrowAccount[] = [
  {
    id: 'esc_1',
    order_id: 'ord_1',
    order_number: 'ORD-2026-88219',
    buyer_id: 'usr_buyer_1',
    buyer_name: 'Grace Mutoni',
    vendor_id: 'usr_vrw_1',
    vendor_name: 'Gishwati Tea Producers Cooperative',
    courier_id: 'usr_courier_1',
    amount_cad: 61.00,
    amount_rwf: 75100,
    status: 'holding',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'esc_2',
    order_id: 'ord_legacy_99',
    order_number: 'ORD-2026-77102',
    buyer_id: 'usr_buyer_1',
    buyer_name: 'Keza Diane',
    vendor_id: 'usr_vrw_1',
    vendor_name: 'Nyamirambo Women’s Center',
    amount_cad: 1450.00,
    amount_rwf: 1788000,
    status: 'fully_released',
    released_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
];

export const INITIAL_DEVICES: UserDevice[] = [
  {
    id: 'dev_1',
    user_id: 'usr_admin_1',
    user_name: 'Emmanuel Habumugisha',
    device_name: 'MacBook Pro 16" (Web Console)',
    os_version: 'macOS 15.1 (Chrome 128)',
    ip_address: '197.243.32.18 (Kigali)',
    is_active: true,
    last_login_at: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: 'dev_2',
    user_id: 'usr_courier_1',
    user_name: 'David Mugisha',
    device_name: 'iPhone 15 Pro (Mobile Web)',
    os_version: 'iOS 17.4 (Safari Mobile)',
    ip_address: '72.138.44.12 (Toronto)',
    is_active: true,
    last_login_at: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 'dev_3',
    user_id: 'usr_vrw_1',
    user_name: 'Gishwati Tea Coop Manager',
    device_name: 'Samsung Galaxy S24',
    os_version: 'Android 14 (Chrome)',
    ip_address: '197.243.10.88 (Kigali)',
    is_active: true,
    last_login_at: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log_1',
    user_id: 'usr_buyer_1',
    user_name: 'Grace Mutoni',
    action: 'Escrow Funds Released (CAD $1,450)',
    category: 'escrow',
    ip_address: '72.138.44.12',
    metadata: { order_number: 'ORD-2026-77102', release_code: 'PIN-8849' },
    created_at: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: 'log_2',
    user_id: 'usr_admin_1',
    user_name: 'System Admin',
    action: 'CBSA Import Manifest Verified (AWB-KGL-88219)',
    category: 'customs',
    ip_address: '197.243.32.18',
    metadata: { manifest: 'AWB-KGL-88219', status: 'CBSA Cleared' },
    created_at: new Date(Date.now() - 1080000).toISOString(),
  },
  {
    id: 'log_3',
    user_id: 'usr_vrw_1',
    user_name: 'Gishwati Tea Coop',
    action: 'New Export Product Registered (TIN-109283745)',
    category: 'auth',
    ip_address: '197.243.10.88',
    metadata: { product: 'Gishwati Organic Black Export Tea', tariff: '0902.30.10' },
    created_at: new Date(Date.now() - 1500000).toISOString(),
  },
];
